# Little script to read npz files

In [1]:
import numpy as np

In [ ]:
file_name = "./example.npz"

In [16]:
donnees = np.load(file_name, allow_pickle=True)
for key in donnees["body_0"].item().keys():
    if isinstance(donnees["body_0"].item()[key], str) or isinstance(donnees["body_0"].item()[key], int):
        print(key,":", donnees["body_0"].item()[key])
    else: 
        print(key,"shape:", donnees["body_0"].item()[key].shape)

model : smplx2020
expressions shape: (183, 50)
trans shape: (183, 3)
betas shape: (183, 10)
poses shape: (183, 165)
gender : neutral
cam_transl shape: (183, 3)
emotions shape: (183,)
emotions_conf shape: (183, 7)
face_bbox_xyxy shape: (183, 4)
flagged_frames shape: (183,)
bbox_xyxy shape: (183, 4)
contacts_conf shape: (183, 6)
face_shape shape: (183, 300)
fps : 30
original_fps : 30
start : 0
stop : 183


In [18]:
print(donnees["body_0"].item()["trans"])

[[ 0.00000000e+00  8.93306971e-01  0.00000000e+00]
 [-1.61023140e-02  8.95189166e-01 -3.93676758e-03]
 [-3.63773108e-02  8.93642664e-01 -8.64791870e-03]
 [-6.07404709e-02  8.91279817e-01 -1.40390396e-02]
 [-8.90265703e-02  8.88156414e-01 -1.99880600e-02]
 [-1.21098280e-01  8.82653713e-01 -2.63357162e-02]
 [-1.56865120e-01  8.75353456e-01 -3.28474045e-02]
 [-1.96210027e-01  8.72502923e-01 -3.91836166e-02]
 [-2.38871217e-01  8.70914578e-01 -4.49075699e-02]
 [-2.84347415e-01  8.72345567e-01 -4.95367050e-02]
 [-3.31884265e-01  8.78712773e-01 -5.26294708e-02]
 [-3.80557775e-01  8.82283211e-01 -5.38797379e-02]
 [-4.29429889e-01  8.89247537e-01 -5.31835556e-02]
 [-4.77721334e-01  8.96103859e-01 -5.06515503e-02]
 [-5.24940968e-01  9.05106544e-01 -4.65784073e-02]
 [-5.70934653e-01  9.09640193e-01 -4.13751602e-02]
 [-6.15844488e-01  9.09034133e-01 -3.54795456e-02]
 [-6.60002112e-01  9.07390356e-01 -2.92797089e-02]
 [-7.03794241e-01  8.98201346e-01 -2.30607986e-02]
 [-7.47528791e-01  8.85214090e-